In [1]:
import numpy as np
import pandas as pd

In [26]:
data=pd.read_csv('datasets/iris.csv',names=['col'+str(i) for i in range(1,4)]+['target'])
data.head()

     col1  col2  col3       target
5.1   3.5   1.4   0.2  Iris-setosa
4.9   3.0   1.4   0.2  Iris-setosa
4.7   3.2   1.3   0.2  Iris-setosa
4.6   3.1   1.5   0.2  Iris-setosa
5.0   3.6   1.4   0.2  Iris-setosa

In [116]:
data.shape

(150, 5)

In [15]:
from sklearn.preprocessing import StandardScaler

In [30]:
ss=StandardScaler()
data=ss.fit_transform(np.array(data.iloc[:,:-1]).T)

In [76]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

In [77]:
data

array([[ 1.320,  1.279,  1.318,  1.265,  1.326,  1.315,  1.325,  1.294,
         1.268,  1.251,  1.315,  1.272,  1.265,  1.330,  1.368,  1.363,
         1.370,  1.331,  1.298,  1.331,  1.249,  1.336,  1.378,  1.279,
         1.198,  1.225,  1.298,  1.302,  1.313,  1.251,  1.239,  1.318,
         1.327,  1.352,  1.251,  1.336,  1.336,  1.251,  1.302,  1.294,
         1.347,  1.225,  1.318,  1.330,  1.270,  1.293,  1.305,  1.298,
         1.315,  1.306,  0.074,  0.109, -0.048, -0.209, -0.131, -0.051,
         0.079,  0.176, -0.025,  0.033, -0.162,  0.091, -0.162, -0.074,
         0.312,  0.109,  0.000,  0.079, -0.416,  0.000, -0.054,  0.091,
        -0.327, -0.070,  0.054,  0.054, -0.143, -0.172, -0.054,  0.226,
        -0.030,  0.030,  0.091, -0.297,  0.000,  0.195,  0.000, -0.284,
         0.174, -0.091, -0.102,  0.000,  0.000,  0.106, -0.028,  0.162,
         0.084,  0.054,  0.373,  0.058, -0.423, -0.392, -0.411, -0.334,
        -0.432, -0.463, -0.340, -0.400, -0.497, -0.310, -0.183, -0.413,
        -0.371, -0.508, -0.532, -0.318, -0.281, -0.233, -0.635, -0.463,
        -0.371, -0.354, -0.503, -0.333, -0.267, -0.267, -0.267, -0.183,
        -0.463, -0.267, -0.443, -0.148, -0.495, -0.224, -0.340, -0.484,
        -0.299, -0.239, -0.162, -0.314, -0.437, -0.340, -0.392, -0.392,
        -0.392, -0.405, -0.472, -0.299, -0.234, -0.220],
       [-0.220, -0.116, -0.215, -0.084, -0.237, -0.208, -0.234, -0.152,
        -0.091, -0.054, -0.208, -0.102, -0.084, -0.249, -0.373, -0.356,
        -0.382, -0.251, -0.162, -0.252, -0.051, -0.267, -0.413, -0.116,
         0.051,  0.000, -0.162, -0.172, -0.202, -0.054, -0.028, -0.215,
        -0.241, -0.318, -0.054, -0.267, -0.267, -0.054, -0.174, -0.152,
        -0.299,  0.000, -0.215, -0.249, -0.096, -0.150, -0.180, -0.162,
        -0.208, -0.183,  1.186,  1.167,  1.248,  1.316,  1.285,  1.249,
         1.183,  1.127,  1.237,  1.208,  1.298,  1.177,  1.298,  1.260,
         1.039,  1.167,  1.225,  1.183,  1.379,  1.225,  1.251,  1.177,
         1.355,  1.258,  1.197,  1.197,  1.290,  1.302,  1.251,  1.096,
         1.240,  1.209,  1.177,  1.346,  1.225,  1.115,  1.225,  1.342,
         1.129,  1.268,  1.272,  1.225,  1.225,  1.168,  1.239,  1.136,
         1.180,  1.197,  0.995,  1.195,  1.380,  1.373,  1.377,  1.357,
         1.382,  1.389,  1.359,  1.375,  1.395,  1.350,  1.306,  1.378,
         1.367,  1.397,  1.401,  1.352,  1.341,  1.324,  1.412,  1.389,
         1.367,  1.363,  1.396,  1.357,  1.336,  1.336,  1.336,  1.306,
         1.389,  1.336,  1.385,  1.292,  1.395,  1.321,  1.359,  1.393,
         1.347,  1.327,  1.298,  1.351,  1.383,  1.359,  1.373,  1.373,
         1.373,  1.376,  1.390,  1.347,  1.325,  1.320],
       [-1.100, -1.162, -1.103, -1.180, -1.089, -1.108, -1.091, -1.142,
        -1.177, -1.197, -1.108, -1.171, -1.180, -1.081, -0.995, -1.008,
        -0.988, -1.080, -1.136, -1.079, -1.198, -1.069, -0.965, -1.162,
        -1.249, -1.225, -1.136, -1.130, -1.111, -1.197, -1.210, -1.103,
        -1.086, -1.034, -1.197, -1.069, -1.069, -1.197, -1.129, -1.142,
        -1.047, -1.225, -1.103, -1.081, -1.174, -1.143, -1.125, -1.136,
        -1.108, -1.123, -1.260, -1.275, -1.200, -1.107, -1.154, -1.198,
        -1.262, -1.303, -1.212, -1.241, -1.136, -1.268, -1.136, -1.186,
        -1.350, -1.275, -1.225, -1.262, -0.962, -1.225, -1.197, -1.268,
        -1.028, -1.188, -1.251, -1.251, -1.147, -1.130, -1.197, -1.322,
        -1.209, -1.240, -1.268, -1.049, -1.225, -1.311, -1.225, -1.058,
        -1.302, -1.177, -1.171, -1.225, -1.225, -1.274, -1.210, -1.298,
        -1.265, -1.251, -1.368, -1.253, -0.957, -0.981, -0.966, -1.023,
        -0.950, -0.926, -1.019, -0.975, -0.898, -1.040, -1.123, -0.965,
        -0.997, -0.889, -0.869, -1.034, -1.060, -1.092, -0.777, -0.926,
        -0.997, -1.009, -0.893, -1.024, -1.069, -1.069, -1.069, -1.123,
        -0.926, -1.069, -0.942, -1.144, -0.900, -1.097, -1.019, -0.908,
        -1.047, -1.087, -1.136, -1.037, -0.946, -1.019, -0.981, -0.981,
        -0.981, -0.971, -0.919, -1.047, -1.091, -1.100]])

In [78]:
cov_matrix=np.cov(data)

In [79]:
cov_matrix

array([[ 0.525, -0.501, -0.023],
       [-0.501,  0.491,  0.010],
       [-0.023,  0.010,  0.013]])

In [80]:
eigvalues, eigvectors = np.linalg.eig(cov_matrix)

In [81]:
eigvalues

array([ 1.010, -0.000,  0.019])

In [82]:
eigvectors

array([[-0.719,  0.577, -0.387],
       [ 0.695,  0.577, -0.429],
       [ 0.024,  0.577,  0.816]])

In [85]:
pc1 = np.dot(data.T,eigvectors[0])
pc2 = np.dot(data.T,eigvectors[1])
pc3 = np.dot(data.T,eigvectors[2])

In [87]:
pc1,pc2,pc3

(array([-0.649, -0.536, -0.644, -0.500, -0.668, -0.636, -0.664, -0.575,
        -0.507, -0.467, -0.636, -0.520, -0.500, -0.681, -0.813, -0.795,
        -0.822, -0.683, -0.586, -0.685, -0.463, -0.700, -0.855, -0.536,
        -0.348, -0.406, -0.586, -0.597, -0.630, -0.467, -0.437, -0.644,
        -0.673, -0.755, -0.467, -0.700, -0.700, -0.467, -0.599, -0.575,
        -0.735, -0.406, -0.644, -0.681, -0.513, -0.573, -0.606, -0.586,
        -0.636, -0.609,  1.120,  1.090,  1.220,  1.339,  1.283,  1.222,
         1.116,  1.029,  1.202,  1.155,  1.306,  1.106,  1.306,  1.240,
         0.899,  1.090,  1.182,  1.116,  1.468,  1.182,  1.225,  1.106,
         1.416,  1.237,  1.137,  1.137,  1.292,  1.313,  1.225,  0.983,
         1.206,  1.157,  1.106,  1.397,  1.182,  1.012,  1.182,  1.389,
         1.031,  1.253,  1.261,  1.182,  1.182,  1.092,  1.204,  1.042,
         1.111,  1.137,  0.836,  1.133,  1.472,  1.454,  1.465,  1.420,
         1.477,  1.493,  1.423,  1.459,  1.511,  1.405,  1.321,  1.466,
         1.442,  1.516,  1.528,  1.410,  1.387,  1.355,  1.572,  1.493,
         1.442,  1.432,  1.514,  1.419,  1.378,  1.378,  1.378,  1.321,
         1.493,  1.378,  1.483,  1.295,  1.510,  1.349,  1.423,  1.504,
         1.398,  1.359,  1.306,  1.407,  1.479,  1.423,  1.454,  1.454,
         1.454,  1.462,  1.498,  1.398,  1.356,  1.346]),
 array([ 1.262,  1.320,  1.264,  1.336,  1.252,  1.269,  1.253,  1.300,
         1.333,  1.351,  1.269,  1.327,  1.336,  1.244,  1.162,  1.174,
         1.155,  1.243,  1.295,  1.242,  1.353,  1.233,  1.132,  1.320,
         1.398,  1.376,  1.295,  1.290,  1.272,  1.351,  1.363,  1.264,
         1.249,  1.199,  1.351,  1.233,  1.233,  1.351,  1.289,  1.300,
         1.212,  1.376,  1.264,  1.244,  1.330,  1.302,  1.285,  1.295,
         1.269,  1.283,  1.276,  1.296,  1.202,  1.089,  1.145,  1.200,
         1.279,  1.332,  1.217,  1.252,  1.123,  1.286,  1.123,  1.184,
         1.395,  1.296,  1.232,  1.279,  0.919,  1.232,  1.197,  1.286,
         0.996,  1.187,  1.265,  1.265,  1.137,  1.116,  1.197,  1.356,
         1.213,  1.251,  1.286,  1.021,  1.232,  1.341,  1.232,  1.031,
         1.331,  1.173,  1.166,  1.232,  1.232,  1.295,  1.214,  1.325,
         1.282,  1.265,  1.420,  1.267,  0.913,  0.940,  0.924,  0.990,
         0.905,  0.877,  0.985,  0.933,  0.845,  1.010,  1.108,  0.922,
         0.959,  0.835,  0.811,  1.003,  1.033,  1.071,  0.707,  0.877,
         0.959,  0.973,  0.839,  0.991,  1.044,  1.044,  1.044,  1.108,
         0.877,  1.044,  0.895,  1.134,  0.847,  1.078,  0.985,  0.857,
         1.019,  1.066,  1.123,  1.007,  0.901,  0.985,  0.940,  0.940,
         0.940,  0.929,  0.869,  1.019,  1.070,  1.081]),
 array([-0.993, -0.985, -0.993, -0.982, -0.994, -0.993, -0.994, -0.989,
        -0.983, -0.978, -0.993, -0.984, -0.982, -0.995, -0.995, -0.995,
        -0.995, -0.995, -0.990, -0.995, -0.978, -0.995, -0.993, -0.985,
        -0.962, -0.970, -0.990, -0.990, -0.992, -0.978, -0.975, -0.993,
        -0.994, -0.996, -0.978, -0.995, -0.995, -0.978, -0.990, -0.989,
        -0.996, -0.970, -0.993, -0.995, -0.983, -0.989, -0.991, -0.990,
        -0.993, -0.991, -0.342, -0.365, -0.260, -0.148, -0.203, -0.258,
        -0.345, -0.409, -0.276, -0.314, -0.181, -0.353, -0.181, -0.242,
        -0.495, -0.365, -0.292, -0.345,  0.001, -0.292, -0.256, -0.353,
        -0.064, -0.245, -0.329, -0.329, -0.194, -0.175, -0.256, -0.441,
        -0.272, -0.313, -0.353, -0.086, -0.292, -0.421, -0.292, -0.096,
        -0.407, -0.231, -0.223, -0.292, -0.292, -0.363, -0.273, -0.400,
        -0.349, -0.329, -0.533, -0.331,  0.006, -0.017, -0.003, -0.059,
         0.012,  0.035, -0.055, -0.011,  0.061, -0.077, -0.167, -0.001,
        -0.033,  0.069,  0.087, -0.071, -0.097, -0.132,  0.166,  0.035,
        -0.033, -0.045,  0.065, -0.060, -0.107, -0.107, -0.107, -0.167,
         0.035, -0.107,  0.020, -0.192,  0.059, -0.138, -0.055,  0.051,
        -0.084, -0.127, -0.181, -0.074,  0.016, -0.055, -0.017, -0.017,
        -0.017, -0.008,  0.042, -0.084, -0.131, -0.141]))

## PCA

In [105]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [126]:
pca=PCA(n_components=3)

In [127]:
data=pd.read_csv('datasets/iris.csv',names=['col'+str(i) for i in range(1,5)]+['target'])

In [128]:
data.head()

   col1  col2  col3  col4       target
0   5.1   3.5   1.4   0.2  Iris-setosa
1   4.9   3.0   1.4   0.2  Iris-setosa
2   4.7   3.2   1.3   0.2  Iris-setosa
3   4.6   3.1   1.5   0.2  Iris-setosa
4   5.0   3.6   1.4   0.2  Iris-setosa

In [129]:
X=np.array(data.iloc[:,:-1])
y=np.array(data.iloc[:,-1])

In [130]:
ss=StandardScaler()
X=ss.fit_transform(X)
X,y

(array([[-0.901,  1.032, -1.341, -1.313],
        [-1.143, -0.125, -1.341, -1.313],
        [-1.385,  0.338, -1.398, -1.313],
        [-1.507,  0.106, -1.284, -1.313],
        [-1.022,  1.263, -1.341, -1.313],
        [-0.537,  1.958, -1.171, -1.050],
        [-1.507,  0.801, -1.341, -1.182],
        [-1.022,  0.801, -1.284, -1.313],
        [-1.749, -0.356, -1.341, -1.313],
        [-1.143,  0.106, -1.284, -1.444],
        [-0.537,  1.495, -1.284, -1.313],
        [-1.264,  0.801, -1.228, -1.313],
        [-1.264, -0.125, -1.341, -1.444],
        [-1.870, -0.125, -1.512, -1.444],
        [-0.053,  2.189, -1.455, -1.313],
        [-0.174,  3.115, -1.284, -1.050],
        [-0.537,  1.958, -1.398, -1.050],
        [-0.901,  1.032, -1.341, -1.182],
        [-0.174,  1.726, -1.171, -1.182],
        [-0.901,  1.726, -1.284, -1.182],
        [-0.537,  0.801, -1.171, -1.313],
        [-0.901,  1.495, -1.284, -1.050],
        [-1.507,  1.263, -1.569, -1.313],
        [-0.901,  0.569, -1.171, -0.919],
        [-1.264,  0.801, -1.057, -1.313],
        [-1.022, -0.125, -1.228, -1.313],
        [-1.022,  0.801, -1.228, -1.050],
        [-0.780,  1.032, -1.284, -1.313],
        [-0.780,  0.801, -1.341, -1.313],
        [-1.385,  0.338, -1.228, -1.313],
        [-1.264,  0.106, -1.228, -1.313],
        [-0.537,  0.801, -1.284, -1.050],
        [-0.780,  2.420, -1.284, -1.444],
        [-0.416,  2.652, -1.341, -1.313],
        [-1.143,  0.106, -1.284, -1.444],
        [-1.022,  0.338, -1.455, -1.313],
        [-0.416,  1.032, -1.398, -1.313],
        [-1.143,  0.106, -1.284, -1.444],
        [-1.749, -0.125, -1.398, -1.313],
        [-0.901,  0.801, -1.284, -1.313],
        [-1.022,  1.032, -1.398, -1.182],
        [-1.628, -1.745, -1.398, -1.182],
        [-1.749,  0.338, -1.398, -1.313],
        [-1.022,  1.032, -1.228, -0.787],
        [-0.901,  1.726, -1.057, -1.050],
        [-1.264, -0.125, -1.341, -1.182],
        [-0.901,  1.726, -1.228, -1.313],
        [-1.507,  0.338, -1.341, -1.313],
        [-0.658,  1.495, -1.284, -1.313],
        [-1.022,  0.569, -1.341, -1.313],
        [ 1.402,  0.338,  0.535,  0.265],
        [ 0.675,  0.338,  0.422,  0.396],
        [ 1.280,  0.106,  0.649,  0.396],
        [-0.416, -1.745,  0.137,  0.133],
        [ 0.796, -0.588,  0.478,  0.396],
        [-0.174, -0.588,  0.422,  0.133],
        [ 0.553,  0.569,  0.535,  0.528],
        [-1.143, -1.513, -0.261, -0.261],
        [ 0.917, -0.356,  0.478,  0.133],
        [-0.780, -0.819,  0.080,  0.265],
        [-1.022, -2.439, -0.147, -0.261],
        [ 0.069, -0.125,  0.251,  0.396],
        [ 0.190, -1.976,  0.137, -0.261],
        [ 0.311, -0.356,  0.535,  0.265],
        [-0.295, -0.356, -0.090,  0.133],
        [ 1.038,  0.106,  0.365,  0.265],
        [-0.295, -0.125,  0.422,  0.396],
        [-0.053, -0.819,  0.194, -0.261],
        [ 0.432, -1.976,  0.422,  0.396],
        [-0.295, -1.282,  0.080, -0.130],
        [ 0.069,  0.338,  0.592,  0.791],
        [ 0.311, -0.588,  0.137,  0.133],
        [ 0.553, -1.282,  0.649,  0.396],
        [ 0.311, -0.588,  0.535,  0.002],
        [ 0.675, -0.356,  0.308,  0.133],
        [ 0.917, -0.125,  0.365,  0.265],
        [ 1.159, -0.588,  0.592,  0.265],
        [ 1.038, -0.125,  0.706,  0.659],
        [ 0.190, -0.356,  0.422,  0.396],
        [-0.174, -1.051, -0.147, -0.261],
        [-0.416, -1.513,  0.024, -0.130],
        [-0.416, -1.513, -0.033, -0.261],
        [-0.053, -0.819,  0.080,  0.002],
        [ 0.190, -0.819,  0.763,  0.528],
        [-0.537, -0.125,  0.422,  0.396],
        [ 0.190,  0.801,  0.422,  0.528],
        [ 1.038,  0.106,  0.535,  0.396],
        [ 0.553, -1.745,  0.365,  0.133],
        [-0.295, -0.125,  0.194,  0.133],
        [-0.416, -1.282,  0.137,  0.133],
        [-0.416, -1.051,  0.365,  0.002],
        [ 0.311, -0.125,  0.478,  0.265],
        [-0.053, -1.051,  0.137,  0.002],
        [-1.022, -1.745, -0.261, -0.261],
        [-0.295, -0.819,  0.251,  0.133],
        [-0.174, -0.125,  0.251,  0.002],
        [-0.174, -0.356,  0.251,  0.133],
        [ 0.432, -0.356,  0.308,  0.133],
        [-0.901, -1.282, -0.431, -0.130],
        [-0.174, -0.588,  0.194,  0.133],
        [ 0.553,  0.569,  1.275,  1.711],
        [-0.053, -0.819,  0.763,  0.922],
        [ 1.523, -0.125,  1.218,  1.185],
        [ 0.553, -0.356,  1.047,  0.791],
        [ 0.796, -0.125,  1.161,  1.316],
        [ 2.129, -0.125,  1.616,  1.185],
        [-1.143, -1.282,  0.422,  0.659],
        [ 1.765, -0.356,  1.445,  0.791],
        [ 1.038, -1.282,  1.161,  0.791],
        [ 1.644,  1.263,  1.331,  1.711],
        [ 0.796,  0.338,  0.763,  1.054],
        [ 0.675, -0.819,  0.876,  0.922],
        [ 1.159, -0.125,  0.990,  1.185],
        [-0.174, -1.282,  0.706,  1.054],
        [-0.053, -0.588,  0.763,  1.579],
        [ 0.675,  0.338,  0.876,  1.448],
        [ 0.796, -0.125,  0.990,  0.791],
        [ 2.250,  1.726,  1.673,  1.316],
        [ 2.250, -1.051,  1.786,  1.448],
        [ 0.190, -1.976,  0.706,  0.396],
        [ 1.280,  0.338,  1.104,  1.448],
        [-0.295, -0.588,  0.649,  1.054],
        [ 2.250, -0.588,  1.673,  1.054],
        [ 0.553, -0.819,  0.649,  0.791],
        [ 1.038,  0.569,  1.104,  1.185],
        [ 1.644,  0.338,  1.275,  0.791],
        [ 0.432, -0.588,  0.592,  0.791],
        [ 0.311, -0.125,  0.649,  0.791],
        [ 0.675, -0.588,  1.047,  1.185],
        [ 1.644, -0.125,  1.161,  0.528],
        [ 1.886, -0.588,  1.331,  0.922],
        [ 2.492,  1.726,  1.502,  1.054],
        [ 0.675, -0.588,  1.047,  1.316],
        [ 0.553, -0.588,  0.763,  0.396],
        [ 0.311, -1.051,  1.047,  0.265],
        [ 2.250, -0.125,  1.331,  1.448],
        [ 0.553,  0.801,  1.047,  1.579],
        [ 0.675,  0.106,  0.990,  0.791],
        [ 0.190, -0.125,  0.592,  0.791],
        [ 1.280,  0.106,  0.933,  1.185],
        [ 1.038,  0.106,  1.047,  1.579],
        [ 1.280,  0.106,  0.763,  1.448],
        [-0.053, -0.819,  0.763,  0.922],
        [ 1.159,  0.338,  1.218,  1.448],
        [ 1.038,  0.569,  1.104,  1.711],
        [ 1.038, -0.125,  0.820,  1.448],
        [ 0.553, -1.282,  0.706,  0.922],
        [ 0.796, -0.125,  0.820,  1.054],
        [ 0.432,  0.801,  0.933,  1.448],
        [ 0.069, -0.125,  0.763,  0.791]]),
 array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica'], dtype=object))

In [131]:
X=pca.fit_transform(X)

In [132]:
X

array([[-2.265,  0.506,  0.122],
       [-2.086, -0.655,  0.227],
       [-2.368, -0.318, -0.051],
       [-2.304, -0.575, -0.099],
       [-2.389,  0.675, -0.021],
       [-2.071,  1.519, -0.031],
       [-2.446,  0.075, -0.342],
       [-2.234,  0.248,  0.083],
       [-2.342, -1.095, -0.154],
       [-2.189, -0.449,  0.247],
       [-2.163,  1.071,  0.264],
       [-2.327,  0.159, -0.100],
       [-2.224, -0.709,  0.223],
       [-2.640, -0.938, -0.190],
       [-2.192,  1.890,  0.469],
       [-2.251,  2.722, -0.033],
       [-2.203,  1.514,  0.001],
       [-2.190,  0.514,  0.039],
       [-1.894,  1.431,  0.371],
       [-2.340,  1.158, -0.137],
       [-1.915,  0.430,  0.416],
       [-2.205,  0.952, -0.165],
       [-2.774,  0.490, -0.339],
       [-1.820,  0.107, -0.040],
       [-2.228,  0.162, -0.124],
       [-1.957, -0.608,  0.299],
       [-2.052,  0.266, -0.092],
       [-2.168,  0.552,  0.201],
       [-2.140,  0.337,  0.265],
       [-2.269, -0.315, -0.076],
       [-2.145, -0.484,  0.068],
       [-1.832,  0.445,  0.265],
       [-2.608,  1.828, -0.051],
       [-2.438,  2.185,  0.079],
       [-2.189, -0.449,  0.247],
       [-2.211, -0.184,  0.219],
       [-2.044,  0.685,  0.479],
       [-2.189, -0.449,  0.247],
       [-2.436, -0.882, -0.202],
       [-2.171,  0.293,  0.170],
       [-2.287,  0.468, -0.041],
       [-1.872, -2.328,  0.195],
       [-2.558, -0.454, -0.314],
       [-1.964,  0.497, -0.315],
       [-2.133,  1.171, -0.253],
       [-2.075, -0.692,  0.057],
       [-2.381,  1.151, -0.062],
       [-2.398, -0.362, -0.147],
       [-2.227,  1.025,  0.177],
       [-2.206,  0.032,  0.147],
       [ 1.104,  0.863,  0.686],
       [ 0.732,  0.599,  0.094],
       [ 1.242,  0.615,  0.555],
       [ 0.397, -1.758,  0.019],
       [ 1.073, -0.212,  0.397],
       [ 0.384, -0.591, -0.127],
       [ 0.749,  0.779, -0.149],
       [-0.498, -1.849, -0.256],
       [ 0.926,  0.030,  0.595],
       [ 0.005, -1.029, -0.543],
       [-0.125, -2.658,  0.040],
       [ 0.439, -0.059, -0.207],
       [ 0.552, -1.773,  0.761],
       [ 0.717, -0.185,  0.067],
       [-0.037, -0.433, -0.198],
       [ 0.876,  0.510,  0.504],
       [ 0.348, -0.191, -0.493],
       [ 0.153, -0.791,  0.299],
       [ 1.215, -1.633,  0.479],
       [ 0.157, -1.303,  0.169],
       [ 0.738,  0.402, -0.617],
       [ 0.472, -0.417,  0.263],
       [ 1.228, -0.941,  0.367],
       [ 0.629, -0.417,  0.290],
       [ 0.700, -0.063,  0.445],
       [ 0.874,  0.251,  0.472],
       [ 1.254, -0.083,  0.727],
       [ 1.358,  0.329,  0.261],
       [ 0.662, -0.224, -0.087],
       [-0.047, -1.057,  0.315],
       [ 0.122, -1.564,  0.145],
       [ 0.014, -1.573,  0.237],
       [ 0.236, -0.776,  0.148],
       [ 1.057, -0.637, -0.107],
       [ 0.221, -0.281, -0.668],
       [ 0.432,  0.855, -0.451],
       [ 1.049,  0.522,  0.396],
       [ 1.036, -1.392,  0.685],
       [ 0.067, -0.213, -0.294],
       [ 0.275, -1.330, -0.093],
       [ 0.272, -1.119, -0.098],
       [ 0.623,  0.028,  0.019],
       [ 0.330, -0.989,  0.196],
       [-0.374, -2.018, -0.112],
       [ 0.283, -0.854, -0.134],
       [ 0.089, -0.175, -0.131],
       [ 0.224, -0.380, -0.159],
       [ 0.574, -0.154,  0.270],
       [-0.457, -1.539, -0.196],
       [ 0.252, -0.596, -0.095],
       [ 1.848,  0.872, -1.003],
       [ 1.153, -0.701, -0.531],
       [ 2.206,  0.554,  0.205],
       [ 1.439, -0.050, -0.163],
       [ 1.868,  0.291, -0.394],
       [ 2.754,  0.788,  0.586],
       [ 0.358, -1.560, -0.991],
       [ 2.303,  0.410,  0.654],
       [ 2.002, -0.724,  0.394],
       [ 2.268,  1.921, -0.393],
       [ 1.366,  0.694, -0.283],
       [ 1.599, -0.428, -0.023],
       [ 1.884,  0.414, -0.025],
       [ 1.253, -1.167, -0.582],
       [ 1.464, -0.444, -1.004],
       [ 1.592,  0.677, -0.637],
       [ 1.471,  0.253, -0.037],
       [ 2.437,  2.557,  0.134],
       [ 3.309, -0.002,  0.707],
       [ 1.254, -1.718,  0.265],
       [ 2.040,  0.907, -0.232],
       [ 0.974, -0.571, -0.830],
       [ 2.898,  0.398,  0.861],
       [ 1.329, -0.487,  0.005],
       [ 1.704,  1.014, -0.296],
       [ 1.958,  1.003,  0.423],
       [ 1.172, -0.319, -0.131],
       [ 1.020,  0.066, -0.338],
       [ 1.786, -0.193, -0.270],
       [ 1.865,  0.555,  0.718],
       [ 2.435,  0.247,  0.730],
       [ 2.316,  2.626,  0.500],
       [ 1.860, -0.185, -0.353],
       [ 1.111, -0.296,  0.183],
       [ 1.197, -0.817,  0.163],
       [ 2.801,  0.845,  0.547],
       [ 1.580,  1.072, -0.943],
       [ 1.347,  0.422, -0.180],
       [ 0.923,  0.019, -0.417],
       [ 1.854,  0.672,  0.015],
       [ 2.016,  0.610, -0.426],
       [ 1.903,  0.686, -0.128],
       [ 1.153, -0.701, -0.531],
       [ 2.043,  0.865, -0.335],
       [ 2.002,  1.049, -0.629],
       [ 1.871,  0.383, -0.255],
       [ 1.558, -0.905,  0.025],
       [ 1.521,  0.267, -0.179],
       [ 1.376,  1.016, -0.931],
       [ 0.959, -0.022, -0.529]])

In [133]:
from sklearn.preprocessing import LabelEncoder

In [134]:
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [135]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [136]:
from sklearn.model_selection import train_test_split

In [137]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [138]:
from sklearn.neighbors import KNeighborsClassifier

In [139]:
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [140]:
from sklearn.metrics import accuracy_score

In [141]:
accuracy_score(y_test,knn.predict(X_test))

1.0

# Original Data

In [121]:
data=pd.read_csv('datasets/iris.csv',names=['col'+str(i) for i in range(1,5)]+['target'])

In [122]:
X=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [123]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.2, random_state=2)

In [124]:
knn2=KNeighborsClassifier(n_neighbors=4)
knn2.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [125]:
accuracy_score(y_test,knn2.predict(X_test))

1.0